### ISSUE TITLE
Github / twitter icons wrap in the header at certain widths

### ISSUE THREAD

**Issue by dzello** [orbit-love/orbit-web#34]
See the screenshot here, you should be able to reproduce by sizing the window.

![image](https://user-images.githubusercontent.com/174777/115054430-7c49b400-9ee0-11eb-81f3-91ea1dc07f9c.png)

I'm not sure the best way to fix, perhaps we could reduce space between elements, or tuck one of the links in the header behind a menu?

**Comment by bencgreenberg** [comment]
Investigating now. Thanks for this!
